/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as ProposalsProposalIdRouteImport } from './routes/proposals.$proposalId'

const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsProposalIdRoute = ProposalsProposalIdRouteImport.update({
  id: '/proposals/$proposalId',
  path: '/proposals/$proposalId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/accept-invite': typeof AcceptInviteRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/settings': typeof SettingsRoute
  '/teams': typeof TeamsRoute
  '/proposals/$proposalId': typeof ProposalsProposalIdRoute
}
export interface FileRoutesByTo {
  '/accept-invite': typeof AcceptInviteRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/settings': typeof SettingsRoute
  '/teams': typeof TeamsRoute
  '/proposals/$proposalId': typeof ProposalsProposalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/accept-invite': typeof AcceptInviteRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/settings': typeof SettingsRoute
  '/teams': typeof TeamsRoute
  '/proposals/$proposalId': typeof ProposalsProposalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/accept-invite'
    | '/admin'
    | '/auth'
    | '/discover'
    | '/settings'
    | '/teams'
    | '/proposals/$proposalId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accept-invite'
    | '/admin'
    | '/auth'
    | '/discover'
    | '/settings'
    | '/teams'
    | '/proposals/$proposalId'
  id:
    | '__root__'
    | '/accept-invite'
    | '/admin'
    | '/auth'
    | '/discover'
    | '/settings'
    | '/teams'
    | '/proposals/$proposalId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AcceptInviteRoute: typeof AcceptInviteRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DiscoverRoute: typeof DiscoverRoute
  SettingsRoute: typeof SettingsRoute
  TeamsRoute: typeof TeamsRoute
  ProposalsProposalIdRoute: typeof ProposalsProposalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals/$proposalId': {
      id: '/proposals/$proposalId'
      path: '/proposals/$proposalId'
      fullPath: '/proposals/$proposalId'
      preLoaderRoute: typeof ProposalsProposalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AcceptInviteRoute: AcceptInviteRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DiscoverRoute: DiscoverRoute,
  SettingsRoute: SettingsRoute,
  TeamsRoute: TeamsRoute,
  ProposalsProposalIdRoute: ProposalsProposalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
